// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"example-nunu/internal/handler"
	"example-nunu/internal/repository"
	"example-nunu/internal/server"
	"example-nunu/internal/service"
	"example-nunu/pkg/app"
	"example-nunu/pkg/jwt"
	"example-nunu/pkg/log"
	"example-nunu/pkg/server/http"
	"example-nunu/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler)
	tqAppRepository := repository.NewTqAppRepository(repositoryRepository)
	tqAppService := service.NewTqAppService(serviceService, tqAppRepository)
	job := server.NewJob(logger, tqAppService)
	task := server.NewTask(logger, tqAppService)
	appApp := newApp(httpServer, job, task)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewTqAppRepository, repository.NewTqDeveloperRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewTqAppService, service.NewTqDeveloperService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewTqAppHandler, handler.NewTqDeveloperHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewTask)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,
	task *server.Task,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, job, task), app.WithName("demo-server"))
}
